In \[5\]:

    import numpy as np
    import pandas as pd

    days=['sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun']
    pd.crosstab(pd.Series(days[1:],name='Tomorrow'),
                pd.Series(days[:-1],name='Today'),normalize=1)

Out\[5\]:

| Today    | rain | sun |
|----------|------|-----|
| Tomorrow |      |     |
| rain     | 0.25 | 1.0 |
| sun      | 0.75 | 0.0 |

In \[21\]:

    import numpy as np
    #Current state
    I = np.matrix([[1, 0]])
    #Transition Matrix
    T = np.matrix([[0.75, 0.25],
                   [0, 1]])
    n=10

    T1 = I * T**n

    print (T1)

    [[0.05631351 0.94368649]]

In \[7\]:

    T1 = I * T**10

In \[8\]:

    print (T1)

    [[0.40443707 0.46075058]]

In \[9\]:

    T2 = I* T**20

In \[10\]:

    print (T2)

    [[0.42721234 0.43038355]]

In \[22\]:

    T3 = I* T**1000
    print (T3)

    [[1.15149854e-125 1.00000000e+000]]

In \[ \]: