In \[21\]:

    #Import the required libraries.
    import matplotlib
    import numpy as np
    import matplotlib.pyplot as plt
    %matplotlib inline

In \[22\]:

    # Importing the Boston Housing dataset
    from sklearn.datasets import load_boston
    boston_data = load_boston()
    print(boston_data['DESCR'])

    .. _boston_dataset:

    Boston house prices dataset
    ---------------------------

    **Data Set Characteristics:**  

        :Number of Instances: 506 

        :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

        :Attribute Information (in order):
            - CRIM     per capita crime rate by town
            - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
            - INDUS    proportion of non-retail business acres per town
            - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
            - NOX      nitric oxides concentration (parts per 10 million)
            - RM       average number of rooms per dwelling
            - AGE      proportion of owner-occupied units built prior to 1940
            - DIS      weighted distances to five Boston employment centres
            - RAD      index of accessibility to radial highways
            - TAX      full-value property-tax rate per $10,000
            - PTRATIO  pupil-teacher ratio by town
            - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town
            - LSTAT    % lower status of the population
            - MEDV     Median value of owner-occupied homes in $1000's

        :Missing Attribute Values: None

        :Creator: Harrison, D. and Rubinfeld, D.L.

    This is a copy of UCI ML housing dataset.
    https://archive.ics.uci.edu/ml/machine-learning-databases/housing/


    This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

    The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
    prices and the demand for clean air', J. Environ. Economics & Management,
    vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
    ...', Wiley, 1980.   N.B. Various transformations are used in the table on
    pages 244-261 of the latter.

    The Boston house-price data has been used in many machine learning papers that address regression
    problems.   
         
    .. topic:: References

       - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
       - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.

    C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

        The Boston housing prices dataset has an ethical problem. You can refer to
        the documentation of this function for further details.

        The scikit-learn maintainers therefore strongly discourage the use of this
        dataset unless the purpose of the code is to study and educate about
        ethical issues in data science and machine learning.

        In this special case, you can fetch the dataset from the original
        source::

            import pandas as pd
            import numpy as np


            data_url = "http://lib.stat.cmu.edu/datasets/boston"
            raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
            data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
            target = raw_df.values[1::2, 2]

        Alternative datasets include the California housing dataset (i.e.
        :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
        dataset. You can load the datasets as follows::

            from sklearn.datasets import fetch_california_housing
            housing = fetch_california_housing()

        for the California housing dataset and::

            from sklearn.datasets import fetch_openml
            housing = fetch_openml(name="house_prices", as_frame=True)

        for the Ames housing dataset.
        
      warnings.warn(msg, category=FutureWarning)

In \[23\]:

    # take the boston data
    data = boston_data['data']
    # we will only work with two of the features: INDUS and RM
    x_input = data[:, [2,5]]
    y_target = boston_data['target']

In \[24\]:

    #cost function across an entire dataset (X, t):
    def cost(w1, w2, b, X, t):
        '''
        Evaluate the cost function in a non-vectorized manner for 
        inputs `X` and targets `t`, at weights `w1`, `w2` and `b`.
        '''
        # TODO: write this!
        costs = 0
        for i in range(len(t)):
            y_i = w1 * X[i, 0] + w2 * X[i, 1] + b
            t_i = t[i]
            costs += 0.5 * (y_i - t_i) ** 2
        return costs / len(t)

In \[25\]:

     #vectorized code looks like this:

    def cost_vectorized(w1, w2, b, X, t):
        '''
        Evaluate the cost function in a vectorized manner for 
        inputs `X` and targets `t`, at weights `w1`, `w2` and `b`.
        '''
        # TODO: write this!
        N = len(y_target)
        w = np.array([w1, w2])
        y = np.dot(X, w) + b * np.ones(N)
        return np.sum((y - t)**2) / (2.0 * N)

In \[29\]:

    import time

In \[30\]:

    #Time for non-vectorized code:

    t0 = time.time()
    print(cost(4, 5, 20, x_input, y_target))
    t1 = time.time()
    print(t1 - t0)

    3182.406341674902
    0.04597592353820801

In \[31\]:

    #Time for vectorized code:

    t0 = time.time()
    print(cost_vectorized(4, 5, 20, x_input, y_target))
    t1 = time.time()
    print(t1 - t0)

    3182.4063416749013
    0.051526546478271484

In \[32\]:

    # add an extra feature (column in the input) that are just all ones
    x_in = np.concatenate([x_input, np.ones([np.shape(x_input)[0], 1])], axis=1)
    x_in

Out\[32\]:

    array([[ 2.31 ,  6.575,  1.   ],
           [ 7.07 ,  6.421,  1.   ],
           [ 7.07 ,  7.185,  1.   ],
           ...,
           [11.93 ,  6.976,  1.   ],
           [11.93 ,  6.794,  1.   ],
           [11.93 ,  6.03 ,  1.   ]])

In \[33\]:

    def solve_exactly(X, t):
        '''
        Solve linear regression exactly. (fully vectorized)
        
        Given `X` - NxD matrix of inputs
              `t` - target outputs
        Returns the optimal weights as a D-dimensional vector
        '''
        # TODO: write this!
        N, D = np.shape(X)
        A = np.matmul(X.T, X)
        c = np.dot(X.T, t)
        return np.matmul(np.linalg.inv(A), c)

In \[34\]:

    solve_exactly(x_in, y_target)

Out\[34\]:

    array([ -0.33471389,   7.82205511, -22.89831573])

In \[35\]:

    # Vectorized gradient function
    def gradfn(weights, X, t):
        '''
        Given `weights` - a current "Guess" of what our weights should be
              `X` - matrix of shape (N,D) of input features
              `t` - target y values
        Return gradient of each weight evaluated at the current value
        '''
        # TODO: write this!
        N, D = np.shape(X)
        y_pred = np.matmul(X, weights)
        error = y_pred - t
        return np.matmul(np.transpose(x_in), error) / float(N)

In \[36\]:

    #With this function, we can solve the optimization problem by repeatedly applying gradient descent on  w :

    def solve_via_gradient_descent(X, t, print_every=5000,
                                   niter=100000, alpha=0.005):
        '''
        Given `X` - matrix of shape (N,D) of input features
              `t` - target y values
        Solves for linear regression weights.
        Return weights after `niter` iterations.
        '''
        # TODO: write this!
        N, D = np.shape(X)
        # initialize all the weights to zeros
        w = np.zeros([D])
        for k in range(niter):
            dw = gradfn(w, X, t)
            w = w - alpha*dw
            if k % print_every == 0:
                print('Weight after %d iteration: %s' % (k, str(w)))
        return w

In \[37\]:

    solve_via_gradient_descent( X=x_in, t=y_target)

    Weight after 0 iteration: [1.10241186 0.73047508 0.11266403]
    Weight after 5000 iteration: [-0.48304613  5.10076868 -3.97899253]
    Weight after 10000 iteration: [-0.45397323  5.63413678 -7.6871518 ]
    Weight after 15000 iteration: [ -0.43059857   6.06296553 -10.66851736]
    Weight after 20000 iteration: [ -0.41180532   6.40774447 -13.06553969]
    Weight after 25000 iteration: [ -0.39669551   6.68494726 -14.9927492 ]
    Weight after 30000 iteration: [ -0.38454721   6.90781871 -16.54222851]
    Weight after 35000 iteration: [ -0.37477995   7.08700769 -17.78801217]
    Weight after 40000 iteration: [ -0.36692706   7.23107589 -18.78962409]
    Weight after 45000 iteration: [ -0.36061333   7.34690694 -19.59492155]
    Weight after 50000 iteration: [ -0.35553708   7.44003528 -20.24238191]
    Weight after 55000 iteration: [ -0.35145576   7.5149106  -20.762941  ]
    Weight after 60000 iteration: [ -0.34817438   7.57511047 -21.18147127]
    Weight after 65000 iteration: [ -0.34553614   7.62351125 -21.51797024]
    Weight after 70000 iteration: [ -0.343415     7.66242555 -21.78851591]
    Weight after 75000 iteration: [ -0.34170959   7.69371271 -22.00603503]
    Weight after 80000 iteration: [ -0.34033844   7.71886763 -22.18092072]
    Weight after 85000 iteration: [ -0.33923604   7.73909222 -22.32152908]
    Weight after 90000 iteration: [ -0.3383497    7.75535283 -22.4345784 ]
    Weight after 95000 iteration: [ -0.33763709   7.76842638 -22.52547023]

Out\[37\]:

    array([ -0.33706425,   7.77893565, -22.59853432])

In \[38\]:

    np.linalg.lstsq(x_in, y_target)

    C:\Users\Madarasinghe\AppData\Local\Temp\ipykernel_1424\1328349989.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
    To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
      np.linalg.lstsq(x_in, y_target)

Out\[38\]:

    (array([ -0.33471389,   7.82205511, -22.89831573]),
     array([19807.614505]),
     3,
     array([318.75354429,  75.21961717,   2.10127199]))

In \[ \]: